apiVersion: apps/v1
kind: Deployment
metadata:
  name: pause
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pause
  template:
    metadata:
      labels:
        app: pause
    spec:
      containers:
        - name: pause
          image: registry.aliyuncs.com/google_containers/pause